version: "3.7"
services:
  #Database
  db:
    image: mysql:8.0.35
    restart: unless-stopped
    container_name: db
    tty: true
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%" ##TODO: Check appropriate solution
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping" ]
      timeout: 20s
      retries: 10
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
  #Laravel App
  backend:
    build: ./BE
    container_name: news_backend_container
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./BE:/var/www/html
  #React App
  frontend:
    build: ./FE
    container_name: news_frontend_container
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./FE:/app
networks:
  app-network:
    driver: bridge
